# 数据源配置
spring:
  datasource:
    # 基本配置
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
    username: root
    url: jdbc:mysql:///springboot?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid其他配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间(毫秒)
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，"wall"用于防火墙
#      filters: stat,wall,log4j
      filters: wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*

    # 初始化时执行sql脚本
    # embedded只初始化内存数据库（默认值）,如h2等
    # always为始终执行初始化,never为不执行初始化
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    # schema是一个列表
    # 文件的编码
    sql-script-encoding: utf-8
    # 遇到语句错误时是否继续，若已经执行过某些语句，再执行可能会报错，可以忽略，不会影响程序启动
    continue-on-error: false
    schema: classpath:sql/employee.sql
#      classpath:sql/department.sql
#      classpath:sql/employee.sql
